name: Deploy static site to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./paper    # 👈 folder to deploy
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
